### PR TITLE
Added option to specify template

### PR DESCRIPTION
**Pull request by Xento**
pimatic-hap uses the template attribute to add devices
when you read temperatures from a logfile you can now specify the
template, so that this readings can be displayed in pimatic-hap

### CODE REVIEW

**Comment by sweetpi** [comment]
Sounds good. Why default as empty string? I would prefere no default and required: false instead.

Could you change this?

**Comment by Xento** [comment]
When it's empty, than the template attribute is not touched. 
Oh, required should be false of course.

**Comment by Xento** [comment]
What about this pullrequest?

**Comment by sweetpi** [comment]
Sorry for the really long reply. This was lost in my notifications. I merged it and published a new version.

Thanks for the additions.

**Pull request merged**
